version: "3"

services:
  shop:
    container_name: shopware5
    image: dockware/${FLAVOUR}:${VERSION}
    ports:
      - "22:22" # ssh
      - "80:80" # apache2
      - "443:443" # apache2 https
      - "8888:8888" # watch admin
      - "9998:9998" # watch storefront proxy
      - "9999:9999" # watch storefront
      - "3306:3306" # mysql port
    volumes:
      - shop:/var/www/html
      - db:/var/lib/mysql

    networks:
      - web
    environment:
      - XDEBUG_ENABLED=0

## ***********************************************************************
##  NETWORKS
## ***********************************************************************
networks:
  web:
    external: false

volumes:
  shop:
    external: false
  db:
    external: false
